server:
  undertow:
    io-threads: 8
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
mybatis:
  type-aliases-package: com.game.entity,com.game.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.fanglin.common.core.enums.CodeEnumTypeHandler
mapper:
  before: true
  safe-delete: true
  safe-update: true
  enum-as-simple-type: false
pagehelper:
  offset-as-page-num: true
spring:
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/game?useSSL=false&serverTimezone=CTT&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2000
      pool-name: hikariCP
      connection-timeout: 10000
common:
  static-dir: /data/static/game/
  jedis:
    enable: true
    password: 123456
    host: 172.17.0.1
  sms:
    ali:
      access-key-id: LTAI4Ff7n5i76MNMW7w3QNgu
      access-secret: EC8YR9jVi1WE4rxVigvsev37bzwsZr
  swagger:
    enable: true
    title: 24节气
    description: 24节气API文档
    version: 1.0.0
  http:
    enable: true